import { ThemeProvider } from '@/app/theme-provider'
import { Toaster } from '@/components/ui/toaster'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import ConvexClientProvider from './ConvexClientProvider'
import { Footer } from './footer'
import './globals.css'
import { Header } from './header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} flex min-h-screen flex-col font-sans antialiased`}
      >
        <div className="relative flex min-h-screen flex-col">
          <ConvexClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Toaster />
              <Header />
              {children}
              <Footer />
            </ThemeProvider>
          </ConvexClientProvider>
        </div>
      </body>
    </html>
  )
}
